# Generated by Django 2.2.2 on 2020-03-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200312_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='decription',
            new_name='description',
        ),
    ]
