# Generated by Django 2.2.2 on 2020-03-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200320_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
    ]
